# Generated by Django 6.0.5 on 2026-06-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rms', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=20, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rms.order')),
            ],
        ),
    ]
