# Generated by Django 6.0.5 on 2026-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_alter_orderitem_food_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'PAID'), ('U', 'PENDING')], default='U', max_length=1),
        ),
    ]
